main:
  - name: নীড়
    url: /
    weight: 1
  - name: পরিচিতি
    weight: 1
    url: /about/
    parent: আমিত্ব
  - name: প্রকাশনা/সন্দর্ভ
    url: #
    parent: আমিত্ব
  - name: উইকিমিডিয়া
    url: /about/wikimedia/
    parent: আমিত্ব
  - name: রেজিউমে
    url: /about/resume/
    parent: আমিত্ব
  - name: খেড়োখাতা
    url: /about/kherokhata/
    parent: আমিত্ব
  - name: ছবিটবি
    url: /about/gallery/
    parent: আমিত্ব
  - name: পোস্ট
    url: /posts/
    weight: 3
  # - name: যোগাযোগ
  #   url: /contact/
  #   weight: 4
  - name: ট্যাগ
    url: /tags/
global: 
  - name: "বাংলা লার্নিং মডিউল"
    url: /learn/bengali/
    params:
      label: অবাংলাভাষীদের জন্য বাংলা শিক্ষণ সামগ্রী
  - name: "পরিষদ বাংলা অভিধান"
    url: /read/parisad-bengali-dictionary/
    params:
      label: বাংলা ভাষার সর্বাধুনিক, সর্ববৃহৎ ও সমৃদ্ধ বাংলা অভিধান
  - name: "পরিষদ লোকজ শব্দকোষ"
    url: /read/lokajashobdokosh/
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "পরিষদ সমার্থক শব্দকোষ"
    url: /read/lokajashobdokosh/
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "বাংলা প্রবাদ সংগ্রহ"
    url: /read/lokajashobdokosh/
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "বাঙালির যা যা"
    url: /read/bangalir-ja-ja/
    params:
      label: বাঙালির ভাষা, প্রযুক্তি, সংস্কৃতি সমস্ত কিছু নিয়ে গ্রন্থ
  - name: "Discrete Mathematics in Bengali"
    url: /read/discrete-mathematics/
    params:
      label: বাঙালির ভাষা, প্রযুক্তি, সংস্কৃতি সমস্ত কিছু নিয়ে গ্রন্থ
globallinks:
  - name: "ঐশিক আইটি সেন্টার"
    url: https://itc.aishikrehman.com/
    params:
      label: লক্ষীগঞ্জ বাজার, ঈশ্বরগঞ্জ, ময়মনসিংহ
  - name: "ঐশিক লার্নিং সেন্টার"
    url: https://learn.aishikrehman.com/
    params:
      label: লক্ষীগঞ্জ বাজার, ঈশ্বরগঞ্জ, ময়মনসিংহ
  - name: "বাংলা পরিষদ"
    url: https://bengalicouncil.github.io/